### ISSUE TITLE
Latest transaction not showing

### ISSUE THREAD

**Issue by theedtron** [Abdulkbk/sats-eye#3]
The app is not displaying transactions.
The see more transactions link still has scaffolding
The search transaction by id page has overflowing data. See the attached screenshot
<img width="1072" alt="Screen Shot 2024-03-29 at 7 09 37 AM" src="https://github.com/Abdulkbk/sats-eye/assets/12064702/5387d917-87e1-4efe-89c6-a1397e3c4012">

**Comment by Abdulkbk** [comment]
> The app is not displaying transactions. The see more transactions link still has scaffolding The search transaction by id page has overflowing data. See the attached screenshot <img alt="Screen Shot 2024-03-29 at 7 09 37 AM" width="1072" src="https://private-user-images.githubusercontent.com/12064702/317951502-5387d917-87e1-4efe-89c6-a1397e3c4012.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3MDQ0NzMsIm5iZiI6MTcxMTcwNDE3MywicGF0aCI6Ii8xMjA2NDcwMi8zMTc5NTE1MDItNTM4N2Q5MTctODdlMS00ZWZlLTg5YzYtYTEzOTdlM2M0MDEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI5VDA5MjI1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkYzc2MTQ3ZDcyNWQ0N2Y0NWUxY2QwOWViMDUyY2MyMzUzMDc0NGZjNjE5ZmM2ZWQ3ZTg4OGNiYWI3NmJiZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OBwnZKR3WOfK0Gp8dRwWTy6d8Wbt3wykPwL9VjhEn78">

This  has been fixed

**Comment by Abdulkbk** [comment]
> The app is not displaying transactions.

@yemmyharry it seems the endpoint `transactions/latest` is returning empty array although I have some trx in my node

**Comment by yemmyharry** [comment]
> > The app is not displaying transactions.
> 
> @yemmyharry it seems the endpoint `transactions/latest` is returning empty array although I have some trx in my node

This has been fixed
